config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :projects
  resources :memberships
  resources :materials
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :people
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  validates_presence_of :name 
  belongs_to :job

def self.search(search)
  if search
    job = Job.find_by(title: search)
    if job
      self.where(job_id: job)
    else
      Person.all
    end
  else
    Person.all
  end
end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  
    def index
    @people = Person.search(params[:search])
    end
   
    def new 
      @person = Person.new 
    end
  
    def create
      split_links
      @person = Person.new(person_params)
      if @person.save 
        redirect_to person_path(@person)
      else
        render :new
      end
    end
  
    def show
      @people = Person.all
    end
  
    def edit

    end
  
    def update
      # @person.update(person_params)
      # redirect_to person_path(@person)
    end
  
    def destroy

    end

  
    private
  
    def set_person
      @person = Person.find_by(id: params[:id])
    end
  
    def split_links
      params[:person][:projects] = params[:person][:projects].first.split(",").map(&:strip)
      params[:person][:materials] = params[:person][:materials].first.split(",").map(&:strip)
    end

    # def filter_params
    #   params.fetch(:title, {})
    # end

    # def filter(relation)
    #   return relation unless filter_params.any?
    #   relation.where(filter_params)
    # end

    def person_params
      params.require(:person).permit(
        :name, 
        :address,
        :phone,
        :email,
        :title,
        :agency,
        :notes,
        :search,
        :job_id,
        projects: [],
        materials: []
      )
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_for_helper.rb
module FormForHelper
  def form_for_object_from_param(param)
    form_for_params = params.fetch(param, {})
    form_for_requirements = { person: { param_key: param } }

    JSON.parse(form_for_params.merge(form_for_requirements).to_json,
               object_class: OpenStruct)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def job_categories
    Job.all
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/people_helper.rb
module PeopleHelper

  def producer_title
    Person.where(title: "Producer")
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Larissa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <%
=begin%>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> 
<%
=end%>

  <link rel="stylesheet" href="styles.css"> 
    <%
=begin%>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
<%
=end%>
  </head>

  <body>
    <%= yield %>
        <%
=begin%>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> 
<%
=end%>

  </body>
</html>

app/views/people/index.html.erb
<h1>All My Peoples</h1>
<%= form_tag(people_path, method: :get) do %>
<%= text_field_tag(:search, params[:search]) %>
<%= submit_tag ("Filter") %>
<% end %>  


<% @people.each do |person| %>
  <div><%= link_to person.name, person_path(person) %></div>
<% end %>  

<%= link_to "Add a Contact", new_person_path(@people) %>

app/views/people/new.html.erb
<div><%= link_to "Home", people_path(@people) %></div>
<%= form_for @person do |form| %>

<h3><%= form.label "Name"%></h3>  
<%= form.text_field :name%>

<h3><%= form.label "Job"%></h3>  
  <%= form.collection_select :job_id, Job.all, :id, :title %>

<h3><%= form.label "Agency"%></h3>  
<%= form.text_field :agency%>

<h3><%= form.label "Phone"%></h3>  
<%= form.text_field :phone%>

<h3><%= form.label "Email"%></h3>  
<%= form.text_field :email%>

<h3><%= form.label "Address"%></h3>  
<%= form.text_field :address%>

<h3><%= form.label "Projects"%></h3>  
<%= form.text_field :projects, multiple: true%>

<h3><%= form.label "Materials"%></h3>  
<%= form.text_field :materials%>

<h3><%= form.label "Notes"%></h3>  
<%= form.text_area :notes%>



<%= form.submit "Add Person"%>
<% end %>

app/views/people/producers.html.erb
 <% @people.each do |person| %>
 <% if person.title === "Producer" %>
    <div><%= link_to person.name, person_path(person) %></div>
<% end %> 
<% end %> 

app/views/people/show.html.erb
<div><%= link_to "Home", people_path(Person.all) %></div>
<h2>Name</h2>
<div><%= @person.name %></div>
<h2>Job</h2>
<div><%= @person.job.title %></div>
<h2>Agency</h2>
<div><%= @person.agency%></div>
<h2>Email</h2>
<div><%= @person.email %></div>
<h2>Phone</h2>
<div><%= @person.phone %></div>
<h2>Address</h2>
<div><%= @person.address %></div>


<% if @person.projects.length != 0 %> 
<h2>Projects</h2>
<% @person.projects.each do |project| %>
<li><%= project %></li>
<% end %>
 <% end %> 


<% if @person.materials.length != 0 %> 
<h2>Materials</h2>
<div><% @person.materials.each do |material| %></div>
<li><%= material %></li>
<% end %>
 <% end %> 

<h2>Notes</h2>
<div><%= @person.notes %></div>